[project]
name = 'ai-services'
version = '0.1.0'
requires-python = '>=3.11'
dependencies = [
    'fastapi==0.136.1',
    'uvicorn==0.46.0',
]

[tool.fastapi]
entrypoint = 'src.main:app'

[tool.pytest.ini_options]
pythonpath = ['src']
testpaths = ['tests']

[tool.ruff]
line-length = 120
target-version = 'py311'
